extends: default

rules:
  line-length:
    max: 150
    level: warning
  document-start:
    present: false
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: false
  indentation:
    spaces: 2
    indent-sequences: consistent

ignore: |
  node_modules/
  .venv/
  dashboard/ui/
