---
apiVersion: v1
kind: Namespace
metadata:
  name: contextmesh-system
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    app.kubernetes.io/part-of: contextmesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: contextmesh-ingestion
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    app.kubernetes.io/part-of: contextmesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: contextmesh-graph
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    app.kubernetes.io/part-of: contextmesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: contextmesh-agents
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    app.kubernetes.io/part-of: contextmesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: contextmesh-api
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    app.kubernetes.io/part-of: contextmesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
    app.kubernetes.io/part-of: contextmesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    app.kubernetes.io/part-of: contextmesh
